FROM python:{{ python_version }}-slim

WORKDIR /app


COPY requirements-docker.txt ./


RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements-docker.txt \
    && apt-get purge -y --auto-remove build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY . .

{% if report.has_pyproject %}
RUN pip install --no-cache-dir --no-deps .
{% endif %}

ENV PYTHONUNBUFFERED=1

{% if entry_point %}
CMD ["python", "{{ entry_point }}"]
{% else %}
CMD ["python"]
{% endif %}