# nosec B404: subprocess usage is safe, no shell=True, command is a list
import subprocess  # nosec
import sys as _sys
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from pyforge_deploy.colors import color_text, is_ci_environment

from .docker_engine import detect_dependencies, get_python_version

_sys.modules.setdefault("src.pyforge_deploy.builders.docker", _sys.modules[__name__])


class DockerBuilder:
    """Main class responsible for rendering the Dockerfile template
    and building the Docker image.
    """

    def __init__(
        self,
        entry_point: str | None = None,
        image_tag: str | None = None,
        verbose: bool = False,
    ) -> None:
        self.base_dir: Path = Path.cwd()
        self.verbose: bool = verbose
        if (
            entry_point is not None
            and not entry_point.replace("_", "").replace("-", "").isalnum()
        ):
            raise ValueError(
                color_text(
                    "Error: entry_point must be alphanumeric, underscore, or hyphen.",
                    "red",
                )
            )
        self.entry_point: str | None = entry_point
        # Validate image_tag for Docker safety
        if image_tag is not None and not image_tag.replace("-", "").isalnum():
            raise ValueError(
                color_text("Error: image_tag must be alphanumeric or hyphen.", "red")
            )
        self.image_tag: str = image_tag or self.base_dir.name.lower().replace(" ", "-")
        self.dockerfile_path: Path = self.base_dir / "Dockerfile"
        self.req_docker_path: Path = self.base_dir / "requirements-docker.txt"

    def _generate_docker_requirements(self, final_list: list[str]) -> None:
        """Writes the detected dependencies to requirements-docker.txt."""
        try:
            with open(self.req_docker_path, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by pyforge-deploy AST/Venv scan\n")
                if final_list:
                    for pkg in final_list:
                        f.write(f"{pkg}\n")

            if self.verbose or is_ci_environment():
                print(color_text("\n--- Detected Docker Requirements ---", "blue"))
                if final_list:
                    for pkg in final_list:
                        print(f" -> {pkg}")
                else:
                    print(" (No external dependencies needed!)")
                print(color_text("------------------------------------\n", "blue"))

        except Exception as err:
            raise RuntimeError(
                color_text(
                    f"Error: Failed to write requirements-docker.txt: {err}", "red"
                )
            ) from err

    def render_template(self) -> None:
        """Renders the Dockerfile template based on detected dependencies."""
        python_version: str = get_python_version()

        try:
            report: dict[str, Any] = detect_dependencies(str(self.base_dir))
            self._generate_docker_requirements(report.get("final_list", []))
        except Exception:
            report = {
                "has_pyproject": False,
                "requirement_files": [],
                "final_list": [],
                "detected_imports": [],
                "dev_tools": [],
            }
            self._generate_docker_requirements([])

        current_module_dir: Path = Path(__file__).parent
        templates_dir: Path = current_module_dir.parent / "templates"

        if not templates_dir.exists():
            raise FileNotFoundError(
                color_text(
                    f"Error: Templates directory not found at {templates_dir}", "red"
                )
            )

        env: Environment = Environment(
            loader=FileSystemLoader(str(templates_dir)),
            autoescape=select_autoescape(["j2", "html", "xml"]),
        )

        try:
            template = env.get_template("Dockerfile.j2")
            rendered_content: str = template.render(
                python_version=python_version,
                report=report,
                entry_point=self.entry_point,
            )
        except Exception as err:
            raise RuntimeError(
                color_text(f"Error: Failed to render Dockerfile template: {err}", "red")
            ) from err

        try:
            with open(self.dockerfile_path, "w", encoding="utf-8") as f:
                f.write(rendered_content)
        except Exception as err:
            raise RuntimeError(
                color_text(f"Error: Failed to write Dockerfile: {err}", "red")
            ) from err

    def build_image(self) -> None:
        """Builds the Docker image using the rendered Dockerfile."""
        print(
            color_text(f"Building Docker image with tag: '{self.image_tag}'...", "blue")
        )

        cmd: list[str] = ["docker", "build", "-t", self.image_tag, "."]  # nosec B603: no user input, safe

        try:
            subprocess.run(cmd, check=True, cwd=str(self.base_dir))  # nosec B603
            print(
                color_text(
                    f"Docker image '{self.image_tag}' built successfully!", "green"
                )
            )

            if self.req_docker_path.exists():
                self.req_docker_path.unlink()

        except subprocess.CalledProcessError as err:
            print(color_text(f"Error: Docker build failed: {err}", "red"))
            raise RuntimeError(
                color_text("Docker build process failed. Check the logs above.", "red")
            ) from err
        except FileNotFoundError as err:
            print(color_text(f"Error: Docker executable not found: {err}", "red"))
            raise RuntimeError(
                color_text(
                    "Docker executable not found. Please ensure Docker is installed and available in your PATH.",  # noqa: E501
                    "red",
                )
            ) from err

    def deploy(self) -> None:
        """Main method to render Dockerfile and build the image."""
        self.render_template()
        self.build_image()
